#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum {
    TD_LCTL_A_B = 0,
};

void dance_lctl_a_b_finished(tap_dance_state_t *state, void *user_data) {
    if (state->pressed) {
        // Long press: Send LCtrl + B
        register_code(KC_LCTL);
        tap_code(KC_B);
        unregister_code(KC_LCTL);
    } else {
        // Short press: Send LCtrl + A
        register_code(KC_LCTL);
        tap_code(KC_A);
        unregister_code(KC_LCTL);
    }
}

tap_dance_action_t tap_dance_actions[] = {
    [TD_LCTL_A_B] = ACTION_TAP_DANCE_FN(dance_lctl_a_b_finished),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, TD(TD_LCTL_A_B), TD(TD_LCTL_A_B), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_BSLS), KC_LALT, KC_LGUI, MO(1), LSFT_T(KC_SPC), RSFT_T(KC_ENT), MO(2), KC_BSPC, KC_DEL),
                                                              [1] = LAYOUT(KC_GRV, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_PPLS, KC_CAPS, KC_NO, KC_NO, KC_WBAK, KC_WFWD, KC_NO, KC_LCBR, KC_RCBR, KC_PIPE, KC_LBRC, KC_RBRC, KC_UNDS, KC_LSFT, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_NO, KC_COLN, KC_DQUO, KC_LCTL, KC_NO, KC_NO, RCS(KC_C), RCS(KC_V), KC_NO, LALT(KC_F4), KC_NO, KC_NO, KC_NO, KC_LT, KC_GT, KC_QUES, KC_NUHS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_DEL, KC_TRNS),
                                                              [2] = LAYOUT(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F4, KC_F10, KC_F11, KC_F12, KC_HOME, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_PGDN, KC_LSFT, KC_5, KC_4, KC_3, KC_2, KC_1, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_LCTL, KC_0, KC_9, KC_8, KC_7, KC_6, LCTL(KC_B), KC_PSCR, KC_HOME, KC_END, KC_COMM, KC_DOT, KC_SLSH, KC_NO, KC_TRNS, KC_TRNS, MO(3), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_BTN2, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_D, KC_WH_U, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
qmk flash - kb splitkb / aurora / lily58 - km wen const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
